# Generated by Django 5.1.7 on 2025-03-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentsForm',
            fields=[
                ('Id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('course', models.CharField(max_length=3)),
                ('sports', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('photo', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=300)),
                ('studyCenter', models.CharField(max_length=50)),
            ],
        ),
    ]
