# Generated by Django 5.1.7 on 2025-03-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsform',
            name='course',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='studentsform',
            name='sports',
            field=models.CharField(max_length=50),
        ),
    ]
