# Generated by Django 5.1.7 on 2025-03-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForm', '0003_alter_studentsform_studycenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsform',
            name='course',
            field=models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('BA', 'BA'), ('MA', 'MA')], max_length=5),
        ),
    ]
