# Generated by Django 5.1.7 on 2025-03-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myForm', '0004_alter_studentsform_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsform',
            old_name='sports',
            new_name='sportsActivity',
        ),
    ]
